name: Build
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1 

      - name: Install dependencies
        run: |
          yarn --silent

      - name: Test and Lint
        run: |
          yarn lint
          yarn test:ci

      - name: Production build
        run: |
          yarn build